[package]
name = "sc-executor-polkavm"
version = "0.32.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "PolkaVM executor for Substrate (polkadot v1.15.0)"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = { workspace = true }
polkavm = { workspace = true }
sc-executor-common.workspace = true
sc-executor-common.default-features = true
sp-wasm-interface.workspace = true
sp-wasm-interface.default-features = true
