[package]
name = "pallet-staking-reward-curve"
version = "12.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Reward Curve for FRAME staking pallet (polkadot v1.15.0)"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { features = ["full", "visit"], workspace = true }

[dev-dependencies]
sp-runtime = { default-features = true, path = "../../../primitives/runtime" }
