[package]
name = "sp-block-builder"
version = "34.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "The block builder runtime api. (polkadot v1.15.0)"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api.workspace = true
sp-inherents.workspace = true
sp-runtime.workspace = true

[features]
default = ["std"]
std = ["sp-api/std", "sp-inherents/std", "sp-runtime/std"]
