[package]
name = "bp-asset-hub-rococo"
description = "Primitives of AssetHubRococo parachain runtime. (polkadot v1.15.0)"
version = "0.13.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true

[lints]
workspace = true

[dependencies]
codec = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
frame-support.workspace = true
bp-xcm-bridge-hub-router.workspace = true

[features]
default = ["std"]
std = [
	"bp-xcm-bridge-hub-router/std",
	"codec/std",
	"frame-support/std",
	"scale-info/std",
]
