[package]
name = "pallet-assets"
version = "39.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME asset management pallet (polkadot v1.15.0)"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
impl-trait-for-tuples = "0.2.2"
log = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
sp-runtime.workspace = true
frame-support.workspace = true
frame-system.workspace = true
frame-benchmarking = { optional = true, workspace = true }
sp-core.workspace = true

[dev-dependencies]
sp-std = { default-features = true, path = "../../primitives/std" }
sp-io = { default-features = true, path = "../../primitives/io" }
pallet-balances = { default-features = true, path = "../balances" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"scale-info/std",
	"sp-core/std",
	"sp-runtime/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]
