[package]
name = "binary-merkle-tree"
version = "15.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
description = "A no-std/Substrate compatible library to construct binary merkle tree. (polkadot v1.15.0)"
homepage = "https://substrate.io"

[lints]
workspace = true

[dependencies]
array-bytes = { optional = true, workspace = true, default-features = true }
log = { optional = true, workspace = true }
hash-db = { workspace = true }

[dev-dependencies]
array-bytes = { workspace = true, default-features = true }
env_logger = { workspace = true }
sp-core = { default-features = true, path = "../../primitives/core" }
sp-runtime = { default-features = true, path = "../../primitives/runtime" }

[features]
debug = ["array-bytes", "log"]
default = ["debug", "std"]
std = ["hash-db/std", "log/std"]
