[package]
name = "pallet-asset-conversion-tx-payment"
version = "19.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Pallet to manage transaction payments in assets by converting them to native assets. (polkadot v1.15.0)"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-runtime.workspace = true
frame-support.workspace = true
frame-system.workspace = true
pallet-asset-conversion.workspace = true
pallet-transaction-payment.workspace = true
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }

[dev-dependencies]
sp-core = { path = "../../../primitives/core", default-features = false }
sp-io = { path = "../../../primitives/io", default-features = false }
sp-storage = { path = "../../../primitives/storage", default-features = false }
pallet-assets = { default-features = true, path = "../../assets" }
pallet-balances = { default-features = true, path = "../../balances" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-asset-conversion/std",
	"pallet-transaction-payment/std",
	"scale-info/std",
	"sp-runtime/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-asset-conversion/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"sp-runtime/try-runtime",
]
