[package]
name = "argochain-runtime"
version = "1.0.0"
authors = ["Argo Chain Team"]
description = "Argo chain runtime."
edition = "2021"
build = "build.rs"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = "6.1"
hex-literal = "0.4.1"

# third-party dependencies
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
	"max-encoded-len",
] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
static_assertions = "1.1.0"
log = { version = "0.4.17", default-features = false }

# pallet-asset-conversion: turn on "num-traits" feature
primitive-types = { version = "0.12.0", default-features = false, features = ["codec", "scale-info", "num-traits"] }

# primitives
sp-authority-discovery = { version = "33.0.0", default-features = false }
sp-consensus-babe = { version = "0.39.0", default-features = false }
sp-consensus-grandpa = { version = "20.0.0", default-features = false }
sp-block-builder = { version = "33.0.0", default-features = false }
sp-inherents = { version = "33.0.0", default-features = false }
### node-primitives = { version = "2.0.0", default-features = false }
sp-offchain = { version = "33.0.0", default-features = false }
sp-core = { version = "34.0.0", default-features = false }
sp-std = { version = "14.0.0", default-features = false }
sp-api = { version = "33.0.0", default-features = false }
sp-runtime = { version = "38.0.0", default-features = false }
sp-staking = { version = "33.0.0", default-features = false }
sp-session = { version = "34.0.0", default-features = false }
sp-transaction-pool = { version = "33.0.0", default-features = false }
sp-statement-store = { version = "17.0.0", default-features = false }
sp-version = { version = "36.0.0", default-features = false }
sp-io = { version = "37.0.0", default-features = false }

# frame dependencies
frame-executive = { version = "36.0.0", default-features = false }
frame-benchmarking = { version = "36.0.0", default-features = false }
# frame-benchmarking-pallet-pov = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.14.0" }
frame-support = { version = "36.0.0", default-features = false, features = ["tuples-96"] }
frame-system = { version = "36.1.0", default-features = false }
frame-system-benchmarking = { version = "36.0.0", default-features = false, optional = true }
frame-election-provider-support = { version = "36.0.0", default-features = false }
frame-system-rpc-runtime-api = { version = "33.0.0", default-features = false }
frame-try-runtime = { version = "0.42.0", default-features = false, optional = true }
pallet-alliance = { version = "35.0.0", default-features = false }
pallet-asset-conversion = { version = "18.0.0", default-features = false }
pallet-asset-rate = { version = "15.0.0", default-features = false }
pallet-assets = { version = "37.0.0", default-features = false }
pallet-authority-discovery = { version = "36.0.0", default-features = false }
pallet-authorship = { version = "36.0.0", default-features = false }
pallet-babe = { version = "36.0.0", default-features = false }
pallet-bags-list = { version = "35.0.0", default-features = false }
pallet-balances = { version = "37.0.0", default-features = false }
pallet-bounties = { version = "35.0.0", default-features = false }
pallet-child-bounties = { version = "35.0.0", default-features = false }
pallet-collective = { version = "36.0.0", default-features = false }
pallet-contracts = { version = "35.0.0", default-features = false }
### pallet-contracts-primitives = { version = "24.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.14.0"}
pallet-conviction-voting = { version = "36.0.0", default-features = false }
pallet-core-fellowship = { version = "20.0.0", default-features = false }
pallet-democracy = { version = "36.0.0", default-features = false }
pallet-election-provider-multi-phase = { version = "35.0.0", default-features = false }
pallet-election-provider-support-benchmarking = { version = "35.0.0", default-features = false, optional = true }
pallet-elections-phragmen = { version = "37.0.0", default-features = false }
pallet-fast-unstake = { version = "35.0.0", default-features = false }
pallet-nis = { version = "36.0.0", default-features = false }
pallet-grandpa = { version = "36.0.0", default-features = false }
pallet-im-online = { version = "35.0.0", default-features = false }
pallet-indices = { version = "36.0.0", default-features = false }
pallet-identity = { version = "36.0.0", default-features = false }
pallet-lottery = { version = "36.0.0", default-features = false }
pallet-membership = { version = "36.0.0", default-features = false }
pallet-message-queue = { version = "39.0.0", default-features = false }
pallet-mmr = { version = "35.0.0", default-features = false }
pallet-multisig = { version = "36.0.0", default-features = false }
pallet-nfts = { version = "30.0.0", default-features = false }
pallet-nfts-runtime-api = { version = "22.0.0", default-features = false }
pallet-nft-fractionalization = { version = "18.0.0", default-features = false }
# pallet-nomination-pools = { version = "1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.14.0"}
pallet-nomination-pools = { version = "1.0.0", default-features = false, path = "../frame/nomination-pools"}

pallet-nomination-pools-benchmarking = { version = "1.0.0", default-features = false, optional = true, path = "../frame/nomination-pools/benchmarking" }
pallet-nomination-pools-runtime-api = { version = "31.0.0", default-features = false }
pallet-offences = { version = "35.0.0", default-features = false }
pallet-offences-benchmarking = { version = "36.0.0", default-features = false, optional = true }
pallet-glutton = { version = "22.0.0", default-features = false }
pallet-preimage = { version = "36.0.0", default-features = false }
pallet-proxy = { version = "36.0.0", default-features = false }
pallet-insecure-randomness-collective-flip = { version = "24.0.0", default-features = false }
pallet-ranked-collective = { version = "36.0.0", default-features = false }
pallet-recovery = { version = "36.0.0", default-features = false }
pallet-referenda = { version = "36.0.0", default-features = false }
pallet-remark = { version = "36.0.0", default-features = false }
pallet-root-testing = { version = "12.0.0", default-features = false }
pallet-salary = { version = "21.0.0", default-features = false }
pallet-session = { version = "36.0.0", features = [ "historical" ], default-features = false }
pallet-session-benchmarking = { version = "36.0.0", default-features = false, optional = true }
pallet-staking = { version = "36.0.0", default-features = false }
pallet-staking-reward-curve = { version = "12.0.0", default-features = false }
pallet-staking-runtime-api = { version = "21.0.0", default-features = false }
pallet-state-trie-migration = { version = "37.0.0", default-features = false }
pallet-statement = { version = "18.0.0", default-features = false }
pallet-scheduler = { version = "37.0.0", default-features = false }
pallet-society = { version = "36.0.0", default-features = false }
pallet-sudo = { version = "36.0.0", default-features = false }
pallet-timestamp = { version = "35.0.0", default-features = false }
pallet-tips = { version = "35.0.0", default-features = false }
pallet-treasury = { version = "35.0.0", default-features = false }
pallet-utility = { version = "36.0.0", default-features = false }
pallet-transaction-payment = { version = "36.0.0", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = "36.0.0", default-features = false }
pallet-asset-conversion-tx-payment = { version = "18.0.0", default-features = false }
pallet-asset-tx-payment = { version = "36.0.0", default-features = false }
pallet-transaction-storage = { version = "35.0.0", default-features = false }
pallet-uniques = { version = "36.0.0", default-features = false }
pallet-vesting = { version = "36.0.0", default-features = false }
pallet-whitelist = { version = "35.0.0", default-features = false }

# Frontier
fp-account = { workspace = true, features = ["serde"] }
fp-evm = { workspace = true, features = ["serde"] }
fp-rpc = { workspace = true }
fp-self-contained = { workspace = true, features = ["serde"] }

# Frontier FRAME
pallet-base-fee = { workspace = true }
pallet-dynamic-fee = { workspace = true }
pallet-ethereum = { workspace = true }
pallet-evm = { workspace = true }
pallet-evm-chain-id = { workspace = true }
pallet-evm-precompile-modexp = { workspace = true }
pallet-evm-precompile-sha3fips = { workspace = true }
pallet-evm-precompile-simple = { workspace = true }
pallet-hotfix-sufficients = { workspace = true }

[build-dependencies]
substrate-wasm-builder = { version = "23.0.0", optional = true }
[dependencies.pallet-counter]
path = "../pallets/pallet-counter"
default-features = false
[features]
default = ["std"]
with-tracing = ["frame-executive/with-tracing"]
std = [
	"pallet-whitelist/std",
	"pallet-offences-benchmarking?/std",
	"pallet-election-provider-support-benchmarking?/std",
	"pallet-asset-conversion-tx-payment/std",
	"pallet-asset-tx-payment/std",
	"frame-system-benchmarking?/std",
	"frame-election-provider-support/std",
	"sp-authority-discovery/std",
	"pallet-asset-conversion/std",
	"pallet-assets/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"sp-consensus-babe/std",
	"sp-consensus-grandpa/std",
	"pallet-babe/std",
	"pallet-bags-list/std",
	"pallet-balances/std",
	"pallet-bounties/std",
	"sp-block-builder/std",
	"codec/std",
	"scale-info/std",
	"pallet-collective/std",
	"pallet-contracts/std",
	# "pallet-contracts-primitives/std",
	"pallet-conviction-voting/std",
	"pallet-core-fellowship/std",
	"pallet-democracy/std",
	"pallet-elections-phragmen/std",
	"pallet-fast-unstake/std",
	"frame-executive/std",
	"pallet-nis/std",
	"pallet-grandpa/std",
	"pallet-im-online/std",
	"pallet-indices/std",
	"sp-inherents/std",
	"pallet-lottery/std",
	"pallet-membership/std",
	"pallet-message-queue/std",
	"pallet-mmr/std",
	"pallet-multisig/std",
	"pallet-nomination-pools/std",
	"pallet-nomination-pools-runtime-api/std",
	"pallet-nomination-pools-benchmarking?/std",
	"pallet-identity/std",
	"pallet-scheduler/std",
	### "node-primitives/std",
	"sp-offchain/std",
	"pallet-offences/std",
	"pallet-glutton/std",
	"pallet-preimage/std",
	"pallet-proxy/std",
	"sp-core/std",
	"pallet-insecure-randomness-collective-flip/std",
	"sp-std/std",
	"pallet-session/std",
	"pallet-session-benchmarking?/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-staking/std",
	"pallet-staking-runtime-api/std",
	"pallet-state-trie-migration/std",
	"pallet-statement/std",
	"pallet-salary/std",
	"sp-session/std",
	"pallet-sudo/std",
	"frame-support/std",
	"frame-benchmarking/std",
	# "frame-benchmarking-pallet-pov/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-election-provider-multi-phase/std",
	"pallet-timestamp/std",
	"pallet-tips/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-storage/std",
	"pallet-treasury/std",
	"pallet-asset-rate/std",
	"sp-transaction-pool/std",
	"sp-statement-store/std",
	"pallet-utility/std",
	"sp-version/std",
	"pallet-society/std",
	"pallet-ranked-collective/std",
	"pallet-referenda/std",
	"pallet-remark/std",
	"pallet-root-testing/std",
	"pallet-recovery/std",
	"pallet-uniques/std",
	"pallet-nfts/std",
	"pallet-nfts-runtime-api/std",
	"pallet-nft-fractionalization/std",
	"pallet-vesting/std",
	"log/std",
	"frame-try-runtime?/std",
	"sp-io/std",
	"pallet-child-bounties/std",
	"pallet-alliance/std",
	"substrate-wasm-builder",
	#frontier
	'fp-rpc/std',
	'fp-evm/std',
	'fp-account/std',
	'fp-self-contained/std',
	'pallet-base-fee/std',
	'pallet-dynamic-fee/std',
	'pallet-ethereum/std',
	'pallet-evm/std',
	'pallet-evm-precompile-simple/std',
	'pallet-evm-precompile-sha3fips/std',
	"pallet-evm-precompile-simple/std",
	"pallet-counter/std",

]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	# "frame-benchmarking-pallet-pov/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"pallet-ethereum/runtime-benchmarks",
	"pallet-evm/runtime-benchmarks",
	"pallet-alliance/runtime-benchmarks",
	"pallet-asset-conversion/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-bags-list/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-bounties/runtime-benchmarks",
	"pallet-child-bounties/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-contracts/runtime-benchmarks",
	"pallet-conviction-voting/runtime-benchmarks",
	"pallet-core-fellowship/runtime-benchmarks",
	"pallet-democracy/runtime-benchmarks",
	"pallet-election-provider-multi-phase/runtime-benchmarks",
	"pallet-election-provider-support-benchmarking/runtime-benchmarks",
	"pallet-elections-phragmen/runtime-benchmarks",
	"pallet-fast-unstake/runtime-benchmarks",
	"pallet-nis/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-identity/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-indices/runtime-benchmarks",
	"pallet-lottery/runtime-benchmarks",
	"pallet-membership/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"pallet-mmr/runtime-benchmarks",
	"pallet-multisig/runtime-benchmarks",
	"pallet-nomination-pools-benchmarking/runtime-benchmarks",
	"pallet-offences-benchmarking/runtime-benchmarks",
	"pallet-glutton/runtime-benchmarks",
	"pallet-preimage/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-scheduler/runtime-benchmarks",
	"pallet-ranked-collective/runtime-benchmarks",
	"pallet-referenda/runtime-benchmarks",
	"pallet-recovery/runtime-benchmarks",
	"pallet-remark/runtime-benchmarks",
	"pallet-salary/runtime-benchmarks",
	"pallet-session-benchmarking/runtime-benchmarks",
	"pallet-society/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-state-trie-migration/runtime-benchmarks",
	"pallet-sudo/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-tips/runtime-benchmarks",
	"pallet-transaction-storage/runtime-benchmarks",
	"pallet-treasury/runtime-benchmarks",
	"pallet-asset-rate/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"pallet-uniques/runtime-benchmarks",
	"pallet-nfts/runtime-benchmarks",
	"pallet-nft-fractionalization/runtime-benchmarks",
	"pallet-vesting/runtime-benchmarks",
	"pallet-whitelist/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
]
try-runtime = [
	"frame-try-runtime/try-runtime",
	# "frame-benchmarking-pallet-pov/try-runtime",
	"frame-executive/try-runtime",
	"frame-system/try-runtime",
	"frame-support/try-runtime",
	"pallet-alliance/try-runtime",
	"pallet-asset-conversion/try-runtime",
	"pallet-assets/try-runtime",
	"pallet-authority-discovery/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-babe/try-runtime",
	"pallet-bags-list/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-bounties/try-runtime",
	"pallet-child-bounties/try-runtime",
	"pallet-collective/try-runtime",
	"pallet-contracts/try-runtime",
	"pallet-conviction-voting/try-runtime",
	"pallet-core-fellowship/try-runtime",
	"pallet-democracy/try-runtime",
	"pallet-election-provider-multi-phase/try-runtime",
	"pallet-elections-phragmen/try-runtime",
	"pallet-fast-unstake/try-runtime",
	"pallet-nis/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-im-online/try-runtime",
	"pallet-indices/try-runtime",
	"pallet-identity/try-runtime",
	"pallet-lottery/try-runtime",
	"pallet-membership/try-runtime",
	"pallet-message-queue/try-runtime",
	"pallet-mmr/try-runtime",
	"pallet-multisig/try-runtime",
	"pallet-nomination-pools/try-runtime",
	"pallet-offences/try-runtime",
	"pallet-glutton/try-runtime",
	"pallet-preimage/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-insecure-randomness-collective-flip/try-runtime",
	"pallet-ranked-collective/try-runtime",
	"pallet-recovery/try-runtime",
	"pallet-referenda/try-runtime",
	"pallet-remark/try-runtime",
	"pallet-root-testing/try-runtime",
	"pallet-salary/try-runtime",
	"pallet-session/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-state-trie-migration/try-runtime",
	"pallet-statement/try-runtime",
	"pallet-scheduler/try-runtime",
	"pallet-society/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-tips/try-runtime",
	"pallet-treasury/try-runtime",
	"pallet-asset-rate/try-runtime",
	"pallet-utility/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-asset-conversion-tx-payment/try-runtime",
	"pallet-asset-tx-payment/try-runtime",
	"pallet-transaction-storage/try-runtime",
	"pallet-uniques/try-runtime",
	"pallet-nfts/try-runtime",
	"pallet-nft-fractionalization/try-runtime",
	"pallet-vesting/try-runtime",
	"pallet-whitelist/try-runtime",
]

