[package]
name = "xcm-procedural"
description = "Procedural macros for XCM (polkadot v1.15.0)"
authors.workspace = true
edition.workspace = true
license.workspace = true
version = "10.1.0"
publish = true

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
Inflector = { workspace = true }

[dev-dependencies]
trybuild = { features = ["diff"], workspace = true }
xcm = { default-features = true, path = "..", package = "staging-xcm" }
