[package]
name = "sc-transaction-pool-api"
version = "37.0.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Transaction pool client facing API. (polkadot v1.15.0)"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
codec = { workspace = true, default-features = true }
futures = { workspace = true }
log = { workspace = true, default-features = true }
serde = { features = ["derive"], workspace = true, default-features = true }
thiserror = { workspace = true }
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-core.workspace = true
sp-runtime.workspace = true

[dev-dependencies]
serde_json = { workspace = true, default-features = true }
