[package]
name = "node-runtime-generate-bags"
version = "3.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Bag threshold generation script for pallet-bag-list and kitchensink-runtime. (polkadot v1.15.0)"
publish = false

[lints]
workspace = true

[dependencies]
kitchensink-runtime.workspace = true
generate-bags.workspace = true
generate-bags.default-features = true

# third-party
clap = { features = ["derive"], workspace = true }
