[package]
name = "sc-allocator"
version = "29.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Collection of allocator implementations. (polkadot v1.15.0)"
documentation = "https://docs.rs/sc-allocator"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = { workspace = true, default-features = true }
thiserror = { workspace = true }
sp-core.workspace = true
sp-core.default-features = true
sp-wasm-interface.workspace = true
sp-wasm-interface.default-features = true
