[package]
name = "frame-support-procedural-tools"
version = "13.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Proc macro helpers for procedural macros (polkadot v1.15.0)"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
proc-macro-crate = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { features = ["extra-traits", "full", "visit"], workspace = true }
frame-support-procedural-tools-derive.workspace = true
frame-support-procedural-tools-derive.default-features = true
