[package]
name = "argochain-runtime"
version = "3.0.0"
authors.workspace = true
description = "Substrate node kitchensink runtime. (polkadot v1.15.0)"
edition.workspace = true
build = "build.rs"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# third-party dependencies
codec = { features = [
	"derive",
	"max-encoded-len",
], workspace = true }
scale-info = { features = ["derive", "serde"], workspace = true }
static_assertions = { workspace = true, default-features = true }
log = { workspace = true }
serde_json = { features = ["alloc", "arbitrary_precision"], workspace = true }

# pallet-asset-conversion: turn on "num-traits" feature
primitive-types = { features = ["codec", "num-traits", "scale-info"], workspace = true }
polkadot-sdk = { features = ["runtime", "tuples-96"], workspace = true }
node-primitives.workspace = true
pallet-example-mbm.workspace = true
pallet-example-tasks.workspace = true



# Frontier
fp-account = { workspace = true, features = ["serde"] }
fp-evm = { workspace = true, features = ["serde"] }
fp-rpc = { workspace = true }
fp-self-contained = { workspace = true, features = ["serde"] }
# Frontier FRAME
pallet-base-fee = { workspace = true }
pallet-dynamic-fee = { workspace = true }
pallet-ethereum = { workspace = true }
pallet-evm = { workspace = true }
pallet-evm-chain-id = { workspace = true }
pallet-evm-precompile-modexp = { workspace = true }
pallet-evm-precompile-sha3fips = { workspace = true }
pallet-evm-precompile-simple = { workspace = true }
pallet-hotfix-sufficients = { workspace = true}
pallet-counter={workspace = true}
hex-literal = "0.4.1"


[build-dependencies]
substrate-wasm-builder = { optional = true, workspace = true, default-features = true }

[features]
default = ["std"]
with-tracing = ["polkadot-sdk/with-tracing"]
std = [
	"codec/std",
	"log/std",
	"node-primitives/std",
	"pallet-example-mbm/std",
	"pallet-example-tasks/std",
	"polkadot-sdk/std",
	"primitive-types/std",
	"scale-info/std",
	"serde_json/std",
	"substrate-wasm-builder",
		# Frontier
	"fp-account/std",
	"fp-evm/std",
	"fp-rpc/std",
	"fp-self-contained/std",
	# Frontier FRAME
	"pallet-base-fee/std",
	"pallet-dynamic-fee/std",
	"pallet-ethereum/std",
	"pallet-evm/std",
	"pallet-evm-precompile-modexp/std",
	"pallet-evm-precompile-sha3fips/std",
	"pallet-evm-precompile-simple/std",
	"pallet-counter/std",
]
runtime-benchmarks = [
	"pallet-example-mbm/runtime-benchmarks",
	"pallet-example-tasks/runtime-benchmarks",
	"polkadot-sdk/runtime-benchmarks",
]
try-runtime = [
	"pallet-example-mbm/try-runtime",
	"pallet-example-tasks/try-runtime",
	"polkadot-sdk/try-runtime",
	"pallet-ethereum/runtime-benchmarks",
	"pallet-evm/runtime-benchmarks",
]
experimental = [
	"pallet-example-tasks/experimental",
]

metadata-hash = ["substrate-wasm-builder/metadata-hash"]
