[package]
name = "polkadot-node-subsystem"
description = "Subsystem traits and message definitions and the generated overseer (polkadot v1.15.0)"
version = "17.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
polkadot-overseer.workspace = true
polkadot-overseer.default-features = true
polkadot-node-subsystem-types.workspace = true
polkadot-node-subsystem-types.default-features = true
polkadot-node-jaeger.workspace = true
polkadot-node-jaeger.default-features = true
