[package]
name = "pallet-xcm-bridge-hub"
description = "Module that adds dynamic bridges/lanes support to XCM infrastructure at the bridge hub. (polkadot v1.15.0)"
version = "0.12.1"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true

[lints]
workspace = true

[dependencies]
codec = { workspace = true }
log = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
bp-messages.workspace = true
bp-runtime.workspace = true
bp-xcm-bridge-hub.workspace = true
pallet-bridge-messages.workspace = true
bridge-runtime-common.workspace = true
frame-support.workspace = true
frame-system.workspace = true
sp-core.workspace = true
sp-runtime.workspace = true
sp-std.workspace = true
xcm.workspace = true
xcm-builder.workspace = true
xcm-executor.workspace = true

[dev-dependencies]
bp-header-chain = { default-features = true, path = "../../primitives/header-chain" }
pallet-balances = { default-features = true, path = "../../../substrate/frame/balances" }
sp-io = { default-features = true, path = "../../../substrate/primitives/io" }

[features]
default = ["std"]
std = [
	"bp-messages/std",
	"bp-runtime/std",
	"bp-xcm-bridge-hub/std",
	"bridge-runtime-common/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-bridge-messages/std",
	"scale-info/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
]
runtime-benchmarks = [
	"bridge-runtime-common/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-bridge-messages/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-bridge-messages/try-runtime",
	"sp-runtime/try-runtime",
]
