[package]
name = "sp-keyring"
version = "39.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Keyring support code for the runtime. A set of test accounts. (polkadot v1.15.0)"
documentation = "https://docs.rs/sp-keyring"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
strum = { features = ["derive"], workspace = true }
sp-core.workspace = true
sp-runtime.workspace = true

[features]
default = ["std"]
std = ["sp-core/std", "sp-runtime/std", "strum/std"]
