use crate::{mock::*, Error, Event};
use frame_support::{assert_noop, assert_ok};

#[test]
fn default_value_works() {
    new_test_ext().execute_with(|| {
        // Set the initial block number to 1 to bypass the genesis block for event processing
        System::set_block_number(1);
        
        // Dispatch a signed extrinsic to the blockchain and check if it executes without error.
        assert_ok!(TemplateModule::update_value(RuntimeOrigin::signed(1), 42));
        
        // Retrieve the stored value from the pallet's storage and verify it matches the expected value.
        assert_eq!(TemplateModule::stored_value(), Some(42));
        
        // Check if the event generated by the previous function call matches the expected event format and content.
        System::assert_last_event(Event::ValueUpdated { value: 42, account_id: 1 }.into());
    });
}

#[test]
fn error_on_absent_value() {
    new_test_ext().execute_with(|| {
        // Attempt to execute a function that requires a pre-existing value and verify it raises the expected error.
        assert_noop!(
            TemplateModule::trigger_error(RuntimeOrigin::signed(1)),
            Error::<Test>::MissingValue
        );
    });
}