[package]
name = "polkadot-core-primitives"
version = "15.0.0"
description = "Core Polkadot types used by Relay Chains and parachains. (polkadot v1.15.0)"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
sp-core.workspace = true
sp-runtime.workspace = true
scale-info = { features = ["derive"], workspace = true }
codec = { features = ["derive"], workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"sp-core/std",
	"sp-runtime/std",
]
