[package]
name = "polkadot-voter-bags"
version = "19.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "CLI to generate voter bags for Polkadot runtimes (polkadot v1.15.0)"

[lints]
workspace = true

[dependencies]
clap = { features = ["derive"], workspace = true }
generate-bags.workspace = true
generate-bags.default-features = true
sp-io.workspace = true
sp-io.default-features = true
westend-runtime.workspace = true
