[package]
name = "bp-xcm-bridge-hub"
description = "Primitives of the xcm-bridge-hub pallet. (polkadot v1.15.0)"
version = "0.3.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true

[lints]
workspace = true

[dependencies]
sp-std.workspace = true

[features]
default = ["std"]
std = ["sp-std/std"]
