[package]
name = "frame-benchmarking-cli"
version = "42.0.1"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "CLI for benchmarking FRAME (polkadot v1.15.0)"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = { workspace = true, default-features = true }
chrono = { workspace = true }
clap = { features = ["derive"], workspace = true }
codec = { workspace = true, default-features = true }
comfy-table = { workspace = true }
handlebars = { workspace = true }
Inflector = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
linked-hash-map = { workspace = true }
log = { workspace = true, default-features = true }
rand = { features = ["small_rng"], workspace = true, default-features = true }
rand_pcg = { workspace = true }
serde = { workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
thiserror = { workspace = true }
thousands = { workspace = true }
frame-benchmarking.workspace = true
frame-benchmarking.default-features = true
frame-support.workspace = true
frame-support.default-features = true
frame-system.workspace = true
frame-system.default-features = true
sc-block-builder.workspace = true
sc-block-builder.default-features = true
sc-chain-spec.workspace = true
sc-cli.workspace = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-client-db.workspace = true
sc-executor.workspace = true
sc-executor.default-features = true
sc-service.workspace = true
sc-sysinfo.workspace = true
sc-sysinfo.default-features = true
sp-api.workspace = true
sp-api.default-features = true
sp-blockchain.workspace = true
sp-blockchain.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-database.workspace = true
sp-database.default-features = true
sp-externalities.workspace = true
sp-externalities.default-features = true
sp-genesis-builder.workspace = true
sp-genesis-builder.default-features = true
sp-inherents.workspace = true
sp-inherents.default-features = true
sp-keystore.workspace = true
sp-keystore.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-state-machine.workspace = true
sp-state-machine.default-features = true
sp-storage.workspace = true
sp-storage.default-features = true
sp-trie.workspace = true
sp-trie.default-features = true
sp-io.workspace = true
sp-io.default-features = true
sp-wasm-interface.workspace = true
sp-wasm-interface.default-features = true
gethostname = { workspace = true }

[features]
default = ["rocksdb"]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sc-client-db/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
rocksdb = ["sc-cli/rocksdb", "sc-client-db/rocksdb"]
