[package]
name = "argochain"
version = "1.0.0"
description = "Client node"
authors = ["argochain"]
edition = "2021"
publish = false
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

#[[bin]]
#name = "argochain"

[dependencies]
array-bytes = "6.1"
# clap = { version = "3.1.18", features = ["derive"] }
clap = { version = "4.2.5", features = ["derive"], optional = true }

#clap_complete = { version = "4.0.2", optional = true }
hex-literal = "0.3.4"
codec = { package = "parity-scale-codec", version = "3.6.1" }
rand = "0.8"
jsonrpsee = { version = "0.16.2", features = ["server"] }
hex = { version = "0.4", default-features = false }
serde_json = "1.0.85"
serde = { version = "1.0.163", features = ["derive"] }
log = "0.4.17"
#rand = "0.8"


futures = "0.3.21"
sc-cli = { version = "0.44.0" }
sp-core = { version = "34.0.0" }
sc-executor = { version = "0.39.0" }
sc-service = { version = "0.43.0" }
sc-telemetry = { version = "22.0.0" }
sc-keystore = { version = "32.0.0" }
sp-keystore = { version = "0.40.0" } ###
sc-transaction-pool = { version = "35.0.0" }
sc-transaction-pool-api = { version = "35.0.0" }
sc-consensus-babe = { version = "0.42.0" }
sc-consensus-slots = { version = "0.41.0" }
sp-consensus-babe = { version = "0.39.0" }
sp-consensus-grandpa = { version = "20.0.0", workspace = true, features = ["default"] }
# sc-consensus-uncles = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.14.0" }
sp-consensus = { version = "0.39.1" } ###
sc-consensus = { version = "0.41.0" } ###
sc-consensus-epochs = { version = "0.41.0" }
# sc-finality-grandpa = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.14.0" }
# sc-consensus-grandpa = { version = "0.10.0-dev",  git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.14.0"  }
# sp-finality-grandpa = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.14.0" }
sc-client-api = { version = "35.1.0" }
sc-chain-spec = { version = "35.0.0" }
sc-network = { version = "0.42.0" }
sc-network-common = { version = "0.41.0" }
sp-runtime = { version = "38.0.0", default-features = false }
sp-timestamp = { version = "33.0.0" }
# sp-authorship = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.14.0" }
sp-inherents = { version = "33.0.0" }
sp-offchain = { version = "33.0.0", workspace = true, features = ["default"] }
sp-session = { version = "34.0.0", workspace = true, features = ["default"] }
sp-keyring = { version = "38.0.0" }
sp-transaction-storage-proof = { version = "33.0.0" }
sp-authority-discovery = { version = "33.0.0", default-features = false }
sc-sync-state-rpc = { version = "0.42.0", default-features = false }
sc-sysinfo = { version = "35.0.0" }
sc-network-sync = { version = "0.41.0" }
sc-statement-store = { version = "17.0.0" }
sc-offchain = { version = "37.0.0" }
sc-storage-monitor = { version = "0.22.0" }
sc-network-statement = { version = "0.24.0" }
sp-statement-store = { version = "17.0.0" }
sc-rpc-spec-v2 = { version = "0.42.0" }
sp-transaction-pool = { version = "33.0.0", workspace = true, features = ["default"] }
grandpa = { version = "0.27.0", package = "sc-consensus-grandpa" }
# grandpa-primitives = { version = "4.0.0-dev", package = "sp-consensus-grandpa" , git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.14.0" }
# These dependencies are used for the node template's RPCs
jsonrpc-core = "18.0.0"
sc-rpc = { version = "37.0.0" }
sp-api = { version = "33.0.0" }
sc-rpc-api = { version = "0.41.0" }
# sc-service-test = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.14.0" }
sc-service-test = { version = "2.0.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.14.0" }
sc-block-builder = { version = "0.40.0" }
sp-tracing = { version = "17.0.0" }
sp-blockchain = { version = "35.1.0" }
sp-block-builder = { version = "33.0.0" }
sc-basic-authorship = { version = "0.42.0" }
sc-consensus-babe-rpc = { version = "0.42.0" }
sc-consensus-grandpa-rpc = { version = "0.27.0" }
substrate-frame-rpc-system = { version = "36.0.0" } ###
pallet-transaction-payment-rpc = { version = "38.0.0" }
pallet-transaction-payment-rpc-runtime-api = { version = "36.0.0", workspace = true }
#pallet-contracts-rpc = { version = "4.0.0-dev",  git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.14.0"  }
substrate-state-trie-migration-rpc = { version = "35.0.0" }
sc-authority-discovery = { version = "0.42.0" }
pallet-assets = { version = "37.0.0" }
pallet-asset-tx-payment = { version = "36.0.0" }
pallet-asset-conversion-tx-payment = { version = "18.0.0" }

mmr-rpc = { version = "35.0.1" } ### 
### pallet-beefy-mmr= { version = "28.0.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.14.0" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { version = "36.0.0" }
frame-benchmarking-cli = { version = "40.0.0" }

# frame dependencies
pallet-im-online = { version = "35.0.0" }
frame-system = { version = "36.1.0" }
pallet-transaction-payment = { version = "36.0.0" }
frame-system-rpc-runtime-api = { version = "33.0.0" }

#### node-executor = { version = "3.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.14.0" } ###
# sc-executor= { version = "0.32.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.14.0" }

# Frontier
fc-cli = { path = "../client/cli" }
fc-consensus = { path = "../client/consensus" }
fc-db = { path = "../client/db" }
fc-mapping-sync = { path = "../client/mapping-sync" }
fc-rpc = { path = "../client/rpc" }
fc-rpc-core = { path = "../client/rpc-core" }
fp-consensus = { path = "../primitives/consensus" }
fp-dynamic-fee = { path = "../primitives/dynamic-fee" }
fp-evm = { version = "3.0.0-dev", path = "../primitives/evm", default-features = false }
fp-rpc = { path = "../primitives/rpc" }
fp-storage = { path = "../primitives/storage" }
pallet-evm = { path = "../frame/evm" }
fc-storage = { workspace = true }


# Local Dependencies
argochain-runtime = { version = "1.0.0", path = "../runtime" }
# node-primitives = { version = "2.0.0", default-features = false } ###

[build-dependencies]
substrate-build-script-utils = { version = "11.0.0", optional = true }


clap = { version = "4.2.5", optional = true }
clap_complete = { version = "4.0.2", optional = true }
sc-cli = { version = "0.44.0", optional = true }
frame-benchmarking-cli = { version = "40.0.0", optional = true } ###
#### substrate-frame-cli = { version = "4.0.0-dev", optional = true, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.14.0" } ###
# try-runtime-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.14.0" }


# CLI-specific dependencies
#### try-runtime-cli = { version = "0.10.0-dev", optional = true, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.14.0" } ###
#### node-inspect = { version = "0.9.0-dev", optional = true, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.14.0" } ###

[dev-dependencies]
substrate-cli-test-utils = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.14.0" }
#### substrate-cli-test-utils = { version = "0.1.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.14.0" }



sc-state-db = { version = "0.30.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.14.0" }
sc-client-db = { version = "0.42.0" }
futures = "0.3.21"
tempfile = "3.1.0"
assert_cmd = "2.0.2"
nix = { version = "0.26.1", features = ["signal"] }
serde_json = "1.0"
regex = "1.6.0"
platforms = "3.0"
soketto = "0.7.1"
criterion = { version = "0.4.0", features = ["async_tokio"] }
tokio = { version = "1.22.0", features = ["macros", "time", "parking_lot"] }
tokio-util = { version = "0.7.4", features = ["compat"] }
wait-timeout = "0.2"
substrate-rpc-client = { version = "0.41.0" }
pallet-timestamp = { version = "35.0.0" }



[features]
default = ["cli"]
cli = [
	#### "node-inspect", ###
	"sc-cli",
	"frame-benchmarking-cli",
	#### "substrate-frame-cli", ###
	"sc-service/rocksdb",
	"clap",
	"clap_complete",
	"substrate-build-script-utils",
	#### "try-runtime-cli", ###
]
# Dependencies that are only required if runtime benchmarking should be build.
runtime-benchmarks = [
	"argochain-runtime/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-benchmarking-cli/runtime-benchmarks",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
#### try-runtime = ["argochain-runtime/try-runtime", "try-runtime-cli/try-runtime"] ###
# sc-state-db = { version = "0.30.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.14.0" }