[package]
name = "sp-core-fuzz"
version = "0.1.0"
publish = false
edition.workspace = true
description = "sp-core-fuzz (polkadot v1.15.0)"

[lints]
workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
lazy_static = { workspace = true }
libfuzzer-sys = { workspace = true }
regex = { workspace = true }
sp-core.workspace = true
sp-core.default-features = true

[[bin]]
name = "fuzz_address_uri"
path = "fuzz_targets/fuzz_address_uri.rs"
test = false
doc = false
