[package]
name = "substrate-test-utils"
version = "3.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate test utilities (polkadot v1.15.0)"
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = { workspace = true }
tokio = { features = ["macros", "time"], workspace = true, default-features = true }

[dev-dependencies]
trybuild = { features = ["diff"], workspace = true }
sc-service = { default-features = true, path = "../client/service" }
