[package]
name = "staging-chain-spec-builder"
version = "5.0.0"
authors.workspace = true
edition.workspace = true
build = "build.rs"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = true
description = "Utility for building chain-specification files for Substrate-based runtimes based on `sp-genesis-builder` (polkadot v1.15.0)"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
path = "bin/main.rs"
name = "chain-spec-builder"

[lib]
crate-type = ["rlib"]

[dependencies]
clap = { features = ["derive"], workspace = true }
log = { workspace = true, default-features = true }
sc-chain-spec = { features = ["clap"], workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
sp-tracing.workspace = true
sp-tracing.default-features = true
