[package]
name = "bridge-hub-rococo-emulated-chain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Bridge Hub Rococo emulated chain (polkadot v1.15.0)"
publish = false

[lints]
workspace = true

[dependencies]
sp-core.workspace = true
frame-support.workspace = true
parachains-common.workspace = true
parachains-common.default-features = true
emulated-integration-tests-common.workspace = true
bridge-hub-rococo-runtime.workspace = true
bridge-hub-rococo-runtime.default-features = true
bridge-hub-common.workspace = true
testnet-parachains-constants = { features = ["rococo"], workspace = true, default-features = true }
