[package]
name = "minimal-template"
description = "A minimal template built with Substrate, part of Polkadot Sdk. (polkadot v1.15.0)"
version = "0.1.0"
license = "Unlicense"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

[dependencies]
minimal-template-node.workspace = true
minimal-template-runtime.workspace = true
pallet-minimal-template.workspace = true
pallet-minimal-template.default-features = true
polkadot-sdk-docs.workspace = true
frame.workspace = true
frame.default-features = true

# How we build docs in rust-docs
simple-mermaid = "0.1.1"
docify = { workspace = true }
