[package]
name = "frame-election-provider-solution-type"
version = "14.0.1"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "NPoS Solution Type (polkadot v1.15.0)"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
syn = { features = ["full", "visit"], workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
proc-macro-crate = { workspace = true }

[dev-dependencies]
codec = { workspace = true, default-features = true }
scale-info = { workspace = true, default-features = true }
sp-arithmetic = { default-features = true, path = "../../../primitives/arithmetic" }
# used by generate_solution_type:
frame-election-provider-support = { default-features = true, path = ".." }
frame-support = { default-features = true, path = "../../support" }
trybuild = { workspace = true }
