name: Rust

on:
  push:
    branches: [ "mainnet" ]
  pull_request:
    branches: [ "mainnet" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: sudo apt-get install protobuf-compiler && cargo build --release
    - name: Run tests
      run: cargo test --verbose
