[package]
name = "sc-executor-common"
version = "0.35.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "A set of common definitions that are needed for defining execution engines. (polkadot v1.15.0)"
documentation = "https://docs.rs/sc-executor-common/"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
thiserror = { workspace = true }
wasm-instrument = { workspace = true, default-features = true }
sc-allocator.workspace = true
sc-allocator.default-features = true
sp-maybe-compressed-blob.workspace = true
sp-maybe-compressed-blob.default-features = true
sp-wasm-interface.workspace = true
sp-wasm-interface.default-features = true
polkavm = { workspace = true }

[features]
default = []
